### ISSUE TITLE
Issue-setup express server and prepared routes and controllers for api; also added basic truffle setup for contracts; added bash scripts to run server

### ISSUE THREAD

**Issue by Zeusofsky** [Zeusofsky/ethereum-api#4]
Automated Review Comments
Issues in README.md:
  - (21, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
Issues in bin/www:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in server/app.js:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
Issues in server/app/controllers/api.js:
  - (6, 'Hardcoded string found')
Issues in server/app/controllers/home.js:
  - (5, 'Hardcoded string found')
Issues in server/app/routes/api.js:
  - (3, 'Hardcoded string found')
Issues in server/app/routes/index.js:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in server/app/routes/users.js:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in server/app/views/index.ejs:
  - (6, 'Hardcoded string found')
Issues in server/public/stylesheets/style.css:
  - (4, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
